// Generated by https://quicktype.io
import 'dart:convert';

class Creadores {
  List<Creador> items = new List();
  Creadores();
  Creadores.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final Creador creador = new Creador.fromJsonMap(item);
      items.add(creador);
    }
  }
}

class Creador {
  int id;
  String name;
  String slug;
  String image;
  String imageBackground;
  int gamesCount;
  List<Game> positions;
  List<Game> games;

  Creador({
    this.id,
    this.name,
    this.slug,
    this.image,
    this.imageBackground,
    this.gamesCount,
    this.positions,
    this.games,
  });

  Creador.fromJsonMap(Map<String, dynamic> jsonList) {
    id = jsonList["id"];
    name = jsonList["name"];
    slug = jsonList["slug"];
    image = jsonList["image"];
    imageBackground = jsonList["image_background"];
    gamesCount = jsonList["games_count"];
    games = Games.fromJson(jsonList["games"]).gamesList;
  }

  String getImage() {
    if (this.image == null) {
      return "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-10.jpg";
    }
    return this.image;
  }

  String getImageBack() {
    if (this.imageBackground == null)
      return "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-10.jpg";

    return this.imageBackground;
  }
}

class Game {
  int id;
  String slug;
  String name;
  int added;

  Game({
    this.id,
    this.slug,
    this.name,
    this.added,
  });
  Game.fromJsonMap(Map<String, dynamic> json) {
    id = json["id"];
    slug = json["slug"];
    name = json["name"];
    added = json["added"];
  }
}

class Games {
  final List<Game> gamesList = new List<Game>();
  Games();

  Games.fromJson(List<dynamic> listJson) {
    if (listJson == null) return;
    for (var item in listJson) {
      final Game game = new Game.fromJsonMap(item);
      gamesList.add(game);
    }
  }
}
